# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/sassinak/win_E/GitHub_Codehouse/RP_2025_ENGINEER/Robot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/sassinak/win_E/GitHub_Codehouse/RP_2025_ENGINEER/Robot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sassinak/win_E/GitHub_Codehouse/RP_2025_ENGINEER/Robot/CMakeFiles /media/sassinak/win_E/GitHub_Codehouse/RP_2025_ENGINEER/Robot//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sassinak/win_E/GitHub_Codehouse/RP_2025_ENGINEER/Robot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FIRMWARE.elf

# Build rule for target.
FIRMWARE.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FIRMWARE.elf
.PHONY : FIRMWARE.elf

# fast build rule for target.
FIRMWARE.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/build
.PHONY : FIRMWARE.elf/fast

#=============================================================================
# Target rules for targets named CMSISDSP

# Build rule for target.
CMSISDSP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CMSISDSP
.PHONY : CMSISDSP

# fast build rule for target.
CMSISDSP/fast:
	$(MAKE) $(MAKESILENT) -f Drivers/CMSIS/DSP/Source/CMakeFiles/CMSISDSP.dir/build.make Drivers/CMSIS/DSP/Source/CMakeFiles/CMSISDSP.dir/build
.PHONY : CMSISDSP/fast

#=============================================================================
# Target rules for targets named stm32h7xx_hal_driver

# Build rule for target.
stm32h7xx_hal_driver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stm32h7xx_hal_driver
.PHONY : stm32h7xx_hal_driver

# fast build rule for target.
stm32h7xx_hal_driver/fast:
	$(MAKE) $(MAKESILENT) -f Drivers/stm32h7xx-hal-driver/CMakeFiles/stm32h7xx_hal_driver.dir/build.make Drivers/stm32h7xx-hal-driver/CMakeFiles/stm32h7xx_hal_driver.dir/build
.PHONY : stm32h7xx_hal_driver/fast

#=============================================================================
# Target rules for targets named BMI08x_SensorAPI

# Build rule for target.
BMI08x_SensorAPI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BMI08x_SensorAPI
.PHONY : BMI08x_SensorAPI

# fast build rule for target.
BMI08x_SensorAPI/fast:
	$(MAKE) $(MAKESILENT) -f Drivers/BMI08x_SensorAPI/CMakeFiles/BMI08x_SensorAPI.dir/build.make Drivers/BMI08x_SensorAPI/CMakeFiles/BMI08x_SensorAPI.dir/build
.PHONY : BMI08x_SensorAPI/fast

#=============================================================================
# Target rules for targets named freertos_kernel

# Build rule for target.
freertos_kernel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 freertos_kernel
.PHONY : freertos_kernel

# fast build rule for target.
freertos_kernel/fast:
	$(MAKE) $(MAKESILENT) -f Middlewares/FreeRTOS-Kernel/CMakeFiles/freertos_kernel.dir/build.make Middlewares/FreeRTOS-Kernel/CMakeFiles/freertos_kernel.dir/build
.PHONY : freertos_kernel/fast

#=============================================================================
# Target rules for targets named freertos_kernel_port

# Build rule for target.
freertos_kernel_port: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 freertos_kernel_port
.PHONY : freertos_kernel_port

# fast build rule for target.
freertos_kernel_port/fast:
	$(MAKE) $(MAKESILENT) -f Middlewares/FreeRTOS-Kernel/portable/CMakeFiles/freertos_kernel_port.dir/build.make Middlewares/FreeRTOS-Kernel/portable/CMakeFiles/freertos_kernel_port.dir/build
.PHONY : freertos_kernel_port/fast

#=============================================================================
# Target rules for targets named segger_rtt

# Build rule for target.
segger_rtt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 segger_rtt
.PHONY : segger_rtt

# fast build rule for target.
segger_rtt/fast:
	$(MAKE) $(MAKESILENT) -f Middlewares/SEGGER_RTT/CMakeFiles/segger_rtt.dir/build.make Middlewares/SEGGER_RTT/CMakeFiles/segger_rtt.dir/build
.PHONY : segger_rtt/fast

Targets/DM-MC02-keil/BSP/FreeRTOSConfig.obj: Targets/DM-MC02-keil/BSP/FreeRTOSConfig.c.obj
.PHONY : Targets/DM-MC02-keil/BSP/FreeRTOSConfig.obj

# target to build an object file
Targets/DM-MC02-keil/BSP/FreeRTOSConfig.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/BSP/FreeRTOSConfig.c.obj
.PHONY : Targets/DM-MC02-keil/BSP/FreeRTOSConfig.c.obj

Targets/DM-MC02-keil/BSP/FreeRTOSConfig.i: Targets/DM-MC02-keil/BSP/FreeRTOSConfig.c.i
.PHONY : Targets/DM-MC02-keil/BSP/FreeRTOSConfig.i

# target to preprocess a source file
Targets/DM-MC02-keil/BSP/FreeRTOSConfig.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/BSP/FreeRTOSConfig.c.i
.PHONY : Targets/DM-MC02-keil/BSP/FreeRTOSConfig.c.i

Targets/DM-MC02-keil/BSP/FreeRTOSConfig.s: Targets/DM-MC02-keil/BSP/FreeRTOSConfig.c.s
.PHONY : Targets/DM-MC02-keil/BSP/FreeRTOSConfig.s

# target to generate assembly for a file
Targets/DM-MC02-keil/BSP/FreeRTOSConfig.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/BSP/FreeRTOSConfig.c.s
.PHONY : Targets/DM-MC02-keil/BSP/FreeRTOSConfig.c.s

Targets/DM-MC02-keil/BSP/startup.obj: Targets/DM-MC02-keil/BSP/startup.cpp.obj
.PHONY : Targets/DM-MC02-keil/BSP/startup.obj

# target to build an object file
Targets/DM-MC02-keil/BSP/startup.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/BSP/startup.cpp.obj
.PHONY : Targets/DM-MC02-keil/BSP/startup.cpp.obj

Targets/DM-MC02-keil/BSP/startup.i: Targets/DM-MC02-keil/BSP/startup.cpp.i
.PHONY : Targets/DM-MC02-keil/BSP/startup.i

# target to preprocess a source file
Targets/DM-MC02-keil/BSP/startup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/BSP/startup.cpp.i
.PHONY : Targets/DM-MC02-keil/BSP/startup.cpp.i

Targets/DM-MC02-keil/BSP/startup.s: Targets/DM-MC02-keil/BSP/startup.cpp.s
.PHONY : Targets/DM-MC02-keil/BSP/startup.s

# target to generate assembly for a file
Targets/DM-MC02-keil/BSP/startup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/BSP/startup.cpp.s
.PHONY : Targets/DM-MC02-keil/BSP/startup.cpp.s

Targets/DM-MC02-keil/Core/Src/adc.obj: Targets/DM-MC02-keil/Core/Src/adc.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/adc.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/adc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/adc.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/adc.c.obj

Targets/DM-MC02-keil/Core/Src/adc.i: Targets/DM-MC02-keil/Core/Src/adc.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/adc.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/adc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/adc.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/adc.c.i

Targets/DM-MC02-keil/Core/Src/adc.s: Targets/DM-MC02-keil/Core/Src/adc.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/adc.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/adc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/adc.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/adc.c.s

Targets/DM-MC02-keil/Core/Src/crc.obj: Targets/DM-MC02-keil/Core/Src/crc.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/crc.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/crc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/crc.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/crc.c.obj

Targets/DM-MC02-keil/Core/Src/crc.i: Targets/DM-MC02-keil/Core/Src/crc.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/crc.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/crc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/crc.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/crc.c.i

Targets/DM-MC02-keil/Core/Src/crc.s: Targets/DM-MC02-keil/Core/Src/crc.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/crc.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/crc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/crc.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/crc.c.s

Targets/DM-MC02-keil/Core/Src/dma.obj: Targets/DM-MC02-keil/Core/Src/dma.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/dma.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/dma.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/dma.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/dma.c.obj

Targets/DM-MC02-keil/Core/Src/dma.i: Targets/DM-MC02-keil/Core/Src/dma.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/dma.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/dma.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/dma.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/dma.c.i

Targets/DM-MC02-keil/Core/Src/dma.s: Targets/DM-MC02-keil/Core/Src/dma.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/dma.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/dma.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/dma.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/dma.c.s

Targets/DM-MC02-keil/Core/Src/fdcan.obj: Targets/DM-MC02-keil/Core/Src/fdcan.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/fdcan.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/fdcan.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/fdcan.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/fdcan.c.obj

Targets/DM-MC02-keil/Core/Src/fdcan.i: Targets/DM-MC02-keil/Core/Src/fdcan.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/fdcan.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/fdcan.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/fdcan.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/fdcan.c.i

Targets/DM-MC02-keil/Core/Src/fdcan.s: Targets/DM-MC02-keil/Core/Src/fdcan.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/fdcan.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/fdcan.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/fdcan.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/fdcan.c.s

Targets/DM-MC02-keil/Core/Src/gpio.obj: Targets/DM-MC02-keil/Core/Src/gpio.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/gpio.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/gpio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/gpio.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/gpio.c.obj

Targets/DM-MC02-keil/Core/Src/gpio.i: Targets/DM-MC02-keil/Core/Src/gpio.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/gpio.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/gpio.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/gpio.c.i

Targets/DM-MC02-keil/Core/Src/gpio.s: Targets/DM-MC02-keil/Core/Src/gpio.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/gpio.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/gpio.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/gpio.c.s

Targets/DM-MC02-keil/Core/Src/iwdg.obj: Targets/DM-MC02-keil/Core/Src/iwdg.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/iwdg.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/iwdg.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/iwdg.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/iwdg.c.obj

Targets/DM-MC02-keil/Core/Src/iwdg.i: Targets/DM-MC02-keil/Core/Src/iwdg.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/iwdg.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/iwdg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/iwdg.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/iwdg.c.i

Targets/DM-MC02-keil/Core/Src/iwdg.s: Targets/DM-MC02-keil/Core/Src/iwdg.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/iwdg.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/iwdg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/iwdg.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/iwdg.c.s

Targets/DM-MC02-keil/Core/Src/main.obj: Targets/DM-MC02-keil/Core/Src/main.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/main.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/main.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/main.c.obj

Targets/DM-MC02-keil/Core/Src/main.i: Targets/DM-MC02-keil/Core/Src/main.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/main.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/main.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/main.c.i

Targets/DM-MC02-keil/Core/Src/main.s: Targets/DM-MC02-keil/Core/Src/main.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/main.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/main.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/main.c.s

Targets/DM-MC02-keil/Core/Src/memorymap.obj: Targets/DM-MC02-keil/Core/Src/memorymap.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/memorymap.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/memorymap.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/memorymap.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/memorymap.c.obj

Targets/DM-MC02-keil/Core/Src/memorymap.i: Targets/DM-MC02-keil/Core/Src/memorymap.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/memorymap.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/memorymap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/memorymap.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/memorymap.c.i

Targets/DM-MC02-keil/Core/Src/memorymap.s: Targets/DM-MC02-keil/Core/Src/memorymap.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/memorymap.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/memorymap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/memorymap.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/memorymap.c.s

Targets/DM-MC02-keil/Core/Src/octospi.obj: Targets/DM-MC02-keil/Core/Src/octospi.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/octospi.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/octospi.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/octospi.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/octospi.c.obj

Targets/DM-MC02-keil/Core/Src/octospi.i: Targets/DM-MC02-keil/Core/Src/octospi.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/octospi.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/octospi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/octospi.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/octospi.c.i

Targets/DM-MC02-keil/Core/Src/octospi.s: Targets/DM-MC02-keil/Core/Src/octospi.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/octospi.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/octospi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/octospi.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/octospi.c.s

Targets/DM-MC02-keil/Core/Src/spi.obj: Targets/DM-MC02-keil/Core/Src/spi.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/spi.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/spi.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/spi.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/spi.c.obj

Targets/DM-MC02-keil/Core/Src/spi.i: Targets/DM-MC02-keil/Core/Src/spi.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/spi.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/spi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/spi.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/spi.c.i

Targets/DM-MC02-keil/Core/Src/spi.s: Targets/DM-MC02-keil/Core/Src/spi.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/spi.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/spi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/spi.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/spi.c.s

Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.obj: Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.c.obj

Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.i: Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.c.i

Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.s: Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.c.s

Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.obj: Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.c.obj

Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.i: Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.c.i

Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.s: Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.c.s

Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.obj: Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.c.obj

Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.i: Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.c.i

Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.s: Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.c.s

Targets/DM-MC02-keil/Core/Src/syscalls.obj: Targets/DM-MC02-keil/Core/Src/syscalls.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/syscalls.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/syscalls.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/syscalls.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/syscalls.c.obj

Targets/DM-MC02-keil/Core/Src/syscalls.i: Targets/DM-MC02-keil/Core/Src/syscalls.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/syscalls.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/syscalls.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/syscalls.c.i

Targets/DM-MC02-keil/Core/Src/syscalls.s: Targets/DM-MC02-keil/Core/Src/syscalls.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/syscalls.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/syscalls.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/syscalls.c.s

Targets/DM-MC02-keil/Core/Src/sysmem.obj: Targets/DM-MC02-keil/Core/Src/sysmem.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/sysmem.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/sysmem.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/sysmem.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/sysmem.c.obj

Targets/DM-MC02-keil/Core/Src/sysmem.i: Targets/DM-MC02-keil/Core/Src/sysmem.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/sysmem.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/sysmem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/sysmem.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/sysmem.c.i

Targets/DM-MC02-keil/Core/Src/sysmem.s: Targets/DM-MC02-keil/Core/Src/sysmem.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/sysmem.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/sysmem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/sysmem.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/sysmem.c.s

Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.obj: Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.c.obj

Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.i: Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.c.i

Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.s: Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.c.s

Targets/DM-MC02-keil/Core/Src/tim.obj: Targets/DM-MC02-keil/Core/Src/tim.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/tim.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/tim.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/tim.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/tim.c.obj

Targets/DM-MC02-keil/Core/Src/tim.i: Targets/DM-MC02-keil/Core/Src/tim.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/tim.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/tim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/tim.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/tim.c.i

Targets/DM-MC02-keil/Core/Src/tim.s: Targets/DM-MC02-keil/Core/Src/tim.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/tim.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/tim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/tim.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/tim.c.s

Targets/DM-MC02-keil/Core/Src/usart.obj: Targets/DM-MC02-keil/Core/Src/usart.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/usart.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Src/usart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/usart.c.obj
.PHONY : Targets/DM-MC02-keil/Core/Src/usart.c.obj

Targets/DM-MC02-keil/Core/Src/usart.i: Targets/DM-MC02-keil/Core/Src/usart.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/usart.i

# target to preprocess a source file
Targets/DM-MC02-keil/Core/Src/usart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/usart.c.i
.PHONY : Targets/DM-MC02-keil/Core/Src/usart.c.i

Targets/DM-MC02-keil/Core/Src/usart.s: Targets/DM-MC02-keil/Core/Src/usart.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/usart.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Core/Src/usart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Src/usart.c.s
.PHONY : Targets/DM-MC02-keil/Core/Src/usart.c.s

Targets/DM-MC02-keil/Core/Startup/startup_stm32h723vgtx.obj: Targets/DM-MC02-keil/Core/Startup/startup_stm32h723vgtx.s.obj
.PHONY : Targets/DM-MC02-keil/Core/Startup/startup_stm32h723vgtx.obj

# target to build an object file
Targets/DM-MC02-keil/Core/Startup/startup_stm32h723vgtx.s.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Core/Startup/startup_stm32h723vgtx.s.obj
.PHONY : Targets/DM-MC02-keil/Core/Startup/startup_stm32h723vgtx.s.obj

Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.obj: Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.obj
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.obj

# target to build an object file
Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.obj
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.obj

Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.i: Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.i
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.i

# target to preprocess a source file
Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.i
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.i

Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.s: Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.s
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.s
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c.s

Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.obj: Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.obj
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.obj

# target to build an object file
Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.obj
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.obj

Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.i: Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.i
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.i

# target to preprocess a source file
Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.i
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.i

Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.s: Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.s
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.s
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c.s

Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.obj: Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.obj
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.obj

# target to build an object file
Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.obj
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.obj

Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.i: Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.i
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.i

# target to preprocess a source file
Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.i
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.i

Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.s: Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.s
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.s
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c.s

Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.obj: Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.obj
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.obj

# target to build an object file
Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.obj
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.obj

Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.i: Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.i
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.i

# target to preprocess a source file
Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.i
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.i

Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.s: Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.s
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.s

# target to generate assembly for a file
Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.s
.PHONY : Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c.s

Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.obj: Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.c.obj
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.obj

# target to build an object file
Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.c.obj
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.c.obj

Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.i: Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.c.i
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.i

# target to preprocess a source file
Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.c.i
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.c.i

Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.s: Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.c.s
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.s

# target to generate assembly for a file
Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.c.s
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.c.s

Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.obj: Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.c.obj
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.obj

# target to build an object file
Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.c.obj
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.c.obj

Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.i: Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.c.i
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.i

# target to preprocess a source file
Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.c.i
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.c.i

Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.s: Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.c.s
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.s

# target to generate assembly for a file
Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.c.s
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.c.s

Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.obj: Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.c.obj
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.obj

# target to build an object file
Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.c.obj
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.c.obj

Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.i: Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.c.i
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.i

# target to preprocess a source file
Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.c.i
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.c.i

Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.s: Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.c.s
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.s

# target to generate assembly for a file
Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.c.s
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.c.s

Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.obj: Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.c.obj
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.obj

# target to build an object file
Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.c.obj
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.c.obj

Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.i: Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.c.i
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.i

# target to preprocess a source file
Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.c.i
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.c.i

Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.s: Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.c.s
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.s

# target to generate assembly for a file
Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRMWARE.elf.dir/build.make CMakeFiles/FIRMWARE.elf.dir/Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.c.s
.PHONY : Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BMI08x_SensorAPI"
	@echo "... CMSISDSP"
	@echo "... FIRMWARE.elf"
	@echo "... freertos_kernel"
	@echo "... freertos_kernel_port"
	@echo "... segger_rtt"
	@echo "... stm32h7xx_hal_driver"
	@echo "... Targets/DM-MC02-keil/BSP/FreeRTOSConfig.obj"
	@echo "... Targets/DM-MC02-keil/BSP/FreeRTOSConfig.i"
	@echo "... Targets/DM-MC02-keil/BSP/FreeRTOSConfig.s"
	@echo "... Targets/DM-MC02-keil/BSP/startup.obj"
	@echo "... Targets/DM-MC02-keil/BSP/startup.i"
	@echo "... Targets/DM-MC02-keil/BSP/startup.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/adc.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/adc.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/adc.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/crc.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/crc.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/crc.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/dma.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/dma.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/dma.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/fdcan.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/fdcan.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/fdcan.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/gpio.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/gpio.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/gpio.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/iwdg.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/iwdg.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/iwdg.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/main.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/main.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/main.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/memorymap.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/memorymap.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/memorymap.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/octospi.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/octospi.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/octospi.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/spi.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/spi.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/spi.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_msp.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/stm32h7xx_hal_timebase_tim.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/stm32h7xx_it.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/syscalls.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/syscalls.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/syscalls.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/sysmem.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/sysmem.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/sysmem.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/system_stm32h7xx.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/tim.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/tim.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/tim.s"
	@echo "... Targets/DM-MC02-keil/Core/Src/usart.obj"
	@echo "... Targets/DM-MC02-keil/Core/Src/usart.i"
	@echo "... Targets/DM-MC02-keil/Core/Src/usart.s"
	@echo "... Targets/DM-MC02-keil/Core/Startup/startup_stm32h723vgtx.obj"
	@echo "... Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.obj"
	@echo "... Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.i"
	@echo "... Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.s"
	@echo "... Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.obj"
	@echo "... Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.i"
	@echo "... Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.s"
	@echo "... Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.obj"
	@echo "... Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.i"
	@echo "... Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.s"
	@echo "... Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.obj"
	@echo "... Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.i"
	@echo "... Targets/DM-MC02-keil/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.s"
	@echo "... Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.obj"
	@echo "... Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.i"
	@echo "... Targets/DM-MC02-keil/USB_DEVICE/App/usb_device.s"
	@echo "... Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.obj"
	@echo "... Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.i"
	@echo "... Targets/DM-MC02-keil/USB_DEVICE/App/usbd_cdc_if.s"
	@echo "... Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.obj"
	@echo "... Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.i"
	@echo "... Targets/DM-MC02-keil/USB_DEVICE/App/usbd_desc.s"
	@echo "... Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.obj"
	@echo "... Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.i"
	@echo "... Targets/DM-MC02-keil/USB_DEVICE/Target/usbd_conf.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

